const NAV_ACTIONS = {
  UP: "UP",
  RIGHT: "RIGHT",
  DOWN: "DOWN",
  LEFT: "LEFT",
  TELEPORT: "TELEPORT",
  TELEPORTING: "TELEPORTING",
  TELEPORT_COMPLETE: "TELEPORT_COMPLETE",
  RESET: "RESET",
  CLEAR_ERROR: "CLEAR_ERROR",
};

export default NAV_ACTIONS;
